language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - psql -c 'create database homestead_test;' -U postgres
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
